### ISSUE TITLE
Criticas construtivas

### ISSUE THREAD

**Issue by JhoanDev** [classroom-ufersa/Gerenciamento_Loja_Moveis#4]
## Feedback sobre o código em C na branch main

1. **Aviso ao compilar:** Aparece um aviso ao compilar o código. Certifique-se de verificar o aviso e corrigir qualquer problema que ele esteja apontando. Embora os avisos nem sempre sejam erros graves, é importante tratá-los para garantir a qualidade e a robustez do código.

2. **Modularização :** Sugiro modularizar mais o código, especialmente na main, que parece estar muito grande. Dividir a lógica em funções menores e mais específicas pode tornar o código mais legível, fácil de manter e reutilizável.

No geral, essas são algumas sugestões para aprimorar o código. Parabenizo pelo trabalho realizado!

@roscibely @marcelohenrique0 @NattanFerreira

**Comment by marcelohdev** [comment]
aviso removido e concertado, muito obrigado pelas sugestões!
